version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file: 
      - ./random_coffee_bot/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - internal

  app:
    build: .
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - ./random_coffee_bot/.env
    depends_on:
      - db
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
