version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file: 
      - ./random_coffee_bot/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - ./random_coffee_bot/.env
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
