"""Refactor Setting table to use default_pairing_interval

Revision ID: 4ea998a4229d
Revises: fca3d9d0ceaa
Create Date: 2025-04-19 14:42:00.206925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea998a4229d'
down_revision: Union[str, None] = 'fca3d9d0ceaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('default_pairing_interval', sa.Integer(), nullable=True))
    op.drop_column('setting', 'key')
    op.drop_column('setting', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('value', sa.VARCHAR(), nullable=False))
    op.add_column('setting', sa.Column('key', sa.VARCHAR(), nullable=False))
    op.drop_column('setting', 'default_pairing_interval')
    # ### end Alembic commands ###
