"""Change model Settings

Revision ID: 564525bf3300
Revises: 750186754343
Create Date: 2025-05-23 07:11:13.492478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '564525bf3300'
down_revision: Union[str, None] = '750186754343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('auto_pairing_paused', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'auto_pairing_paused')
    # ### end Alembic commands ###
