"""Change user model: has_permission instead of is_in_group

Revision ID: 831791f2ab61
Revises: fca3d9d0ceaa
Create Date: 2025-04-23 17:09:51.040024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831791f2ab61'
down_revision: Union[str, None] = 'fca3d9d0ceaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column(
            'is_in_group',
            new_column_name='has_permission',
            existing_type=sa.Boolean(),
            existing_nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column(
            'has_permission',
            new_column_name='is_in_group',
            existing_type=sa.Boolean(),
            existing_nullable=False
        )
    # ### end Alembic commands ###
